# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{extlib_lite}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Wilkie"]
  s.date = %q{2010-07-08}
  s.email = %q{dwilkie@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "extlib_lite.gemspec",
     "lib/extlib_lite.rb",
     "lib/extlib_lite/core_extensions.rb",
     "lib/extlib_lite/core_extensions/hash.rb",
     "lib/extlib_lite/core_extensions/string.rb",
     "lib/extlib_lite/inflections.rb",
     "todo"
  ]
  s.homepage = %q{http://github.com/dwilkie/extlib_lite}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Lightweight alternative to activesupport and extlib}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 2.1.1"])
    else
      s.add_dependency(%q<addressable>, [">= 2.1.1"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 2.1.1"])
  end
end

